services:
  - type: web
    name: search-pulse-backend
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
