import PDFDocument from "pdfkit";

/**
 * Generates a premium A4 SEO Audit Report PDF matching the Search Pulse brand.
 * Safe for Render deployment — no system fonts, no emoji in Helvetica, no undefined colors.
 */
export const generateSeoPdf = (scan, res) => {
  // ── Page dimensions ──────────────────────────────────────────
  const PW = 595.28;   // A4 width  (pt)
  const PH = 841.89;   // A4 height (pt)
  const ML = 48;       // left margin
  const MR = 48;       // right margin
  const CW = PW - ML - MR; // content width

  // ── Brand colours ─────────────────────────────────────────────
  const G = {
    green:    "#10b981",
    gDark:    "#059669",
    gTint:    "#ecfdf5",
    gMid:     "#d1fae5",
    blue:     "#0ea5e9",
    purple:   "#8b5cf6",
    indigo:   "#6366f1",
    amber:    "#f59e0b",
    rose:     "#f43f5e",
    s900:     "#0f172a",
    s800:     "#1e293b",
    s700:     "#334155",
    s600:     "#475569",
    s500:     "#64748b",
    s400:     "#94a3b8",
    s300:     "#cbd5e1",
    s200:     "#e2e8f0",
    s100:     "#f1f5f9",
    s50:      "#f8fafc",
    white:    "#ffffff",
  };

  // ── Fonts (built-in, always available on any Node.js env) ─────
  const REG  = "Helvetica";
  const BOLD = "Helvetica-Bold";
  const ITAL = "Helvetica-Oblique";

  // ── PDFKit doc ────────────────────────────────────────────────
  const doc = new PDFDocument({
    size: "A4",
    margin: 0,
    autoFirstPage: false,      // We add pages manually to control decoration
    bufferPages: false,
    info: {
      Title: `Search Pulse SEO Report`,
      Author: "Search Pulse",
      Subject: "SEO Audit Report",
    },
  });

  doc.pipe(res);

  // ── Drawing helpers ───────────────────────────────────────────
  const rr = (x, y, w, h, r, color) =>
    doc.roundedRect(x, y, w, h, r).fillColor(color).fill();

  const rrStroke = (x, y, w, h, r, color, lw = 0.6) =>
    doc.roundedRect(x, y, w, h, r).strokeColor(color).lineWidth(lw).stroke();

  const hrule = (y, color = G.s200, lw = 0.5) =>
    doc.moveTo(ML, y).lineTo(PW - MR, y).strokeColor(color).lineWidth(lw).stroke();

  const txt = (str, x, y, font, size, color, opts = {}) => {
    doc.font(font).fontSize(size).fillColor(color)
       .text(String(str ?? ""), x, y, { lineBreak: false, ...opts });
  };

  // ── Y cursor helpers ──────────────────────────────────────────
  let curY = 0;
  const getY = () => doc.y || curY;
  const setY = (y) => { doc.y = y; curY = y; };
  const addY = (dy) => setY(getY() + dy);

  // Safe usable bottom of page (above footer bar)
  const BOTTOM = PH - 36;

  // ── Page management ───────────────────────────────────────────
  let pageNum = 0;

  const addPage = () => {
    doc.addPage({ size: "A4", margin: 0 });
    pageNum++;
    drawPageChrome(false);
    setY(ML + 36);
  };

  const guard = (heightNeeded) => {
    if (getY() + heightNeeded > BOTTOM) addPage();
  };

  // ── Page chrome (top bar + header + footer) ───────────────────
  const drawPageChrome = (isCover) => {
    // Top green stripe
    doc.rect(0, 0, PW, 5).fillColor(G.green).fill();

    if (!isCover) {
      // Dark header band
      doc.rect(0, 5, PW, 38).fillColor(G.s900).fill();
      txt("SEARCH PULSE   |   SEO Audit Report", ML, 20, BOLD, 8, G.green);
      txt(`Page ${pageNum}`, PW - MR - 38, 20, BOLD, 8, G.s500);
    }

    // Dark footer band
    doc.rect(0, PH - 32, PW, 32).fillColor(G.s900).fill();
    txt("Generated by Search Pulse  |  Confidential",
        ML, PH - 20, ITAL, 6.5, G.s500);
    txt(`(c) ${new Date().getFullYear()} Search Pulse`,
        PW - MR - 90, PH - 20, REG, 6.5, G.s500);

    // Elegant page boundary/border
    doc.rect(12, 12, PW - 24, PH - 24).strokeColor(G.s300).lineWidth(0.8).stroke();
  };

  // ── Section heading ───────────────────────────────────────────
  const sectionHead = (label) => {
    guard(44);
    const y = getY();
    rr(ML, y, 4, 16, 2, G.green);
    txt(label, ML + 12, y + 2, BOLD, 8, G.s600, { characterSpacing: 1 });
    addY(20);
    hrule(getY());
    addY(10);
  };

  // ═════════════════════════════════════════════════════════════
  // PAGE 1 — COVER
  // ═════════════════════════════════════════════════════════════
  doc.addPage({ size: "A4", margin: 0 });
  pageNum = 1;
  drawPageChrome(true);

  // Hero dark block
  const HERO_H = 210;
  doc.rect(0, 5, PW, HERO_H).fillColor(G.s900).fill();

  // Subtle decorative circles (solid low-opacity approximation)
  doc.circle(PW - 70, 70, 85).fillColor(G.s800).fill();
  doc.circle(60, 165, 55).fillColor(G.s800).fill();

  // Brand badge
  rr(ML, 22, 118, 22, 11, G.green);
  txt(">> SEARCH PULSE", ML + 10, 28, BOLD, 8, G.white, { characterSpacing: 0.5 });

  // Title — single line to prevent overlap
  txt("SEO Audit Report", ML, 74, BOLD, 26, G.white);
  txt("Comprehensive website analysis powered by AI", ML, 116, REG, 9.5, G.s400);

  // URL pill
  const displayUrl = scan.url || "";
  const urlText = `[URL]  ${displayUrl}`;
  doc.font(BOLD).fontSize(8.5);
  const textWidth = doc.widthOfString(urlText);
  const pillWidth = Math.min(CW, textWidth + 24);
  rr(ML, 136, pillWidth, 24, 12, G.s800);
  txt(urlText, ML + 12, 143, BOLD, 8.5, G.green, { width: pillWidth - 24, lineBreak: false, ellipsis: true });

  // Date
  const crawlDate = new Date(scan.createdAt || Date.now()).toLocaleDateString("en-US", {
    weekday: "short", year: "numeric", month: "short", day: "numeric",
  });
  txt("Crawled: " + crawlDate, ML, 172, REG, 8, G.s500);

  // ── Score pills row ───────────────────────────────────────────
  const scoreData = [
    { label: "SEO Score",    value: Math.round(scan.scores?.seo || 0),          color: G.green  },
    { label: "Performance",  value: Math.round(scan.scores?.performance || 0),   color: G.blue   },
    { label: "Accessibility",value: Math.round(scan.scores?.accessibility || 0), color: G.purple },
    { label: "Best Practices",value: Math.round(scan.scores?.bestPractices || 0),color: G.indigo },
  ];

  const PILL_W = 116, PILL_H = 74, PILL_GAP = 7;
  const pillsW = PILL_W * 4 + PILL_GAP * 3;
  const pillX0 = (PW - pillsW) / 2;
  const PILL_Y = HERO_H + 5 + 12;

  scoreData.forEach((s, i) => {
    const px = pillX0 + i * (PILL_W + PILL_GAP);
    // Card
    doc.rect(px, PILL_Y, PILL_W, PILL_H).fillColor(G.white).fill();
    rrStroke(px, PILL_Y, PILL_W, PILL_H, 0, G.s200, 0.5);
    // Top colour bar
    doc.rect(px, PILL_Y, PILL_W, 4).fillColor(s.color).fill();
    // Score
    txt(`${s.value}%`, px + 6, PILL_Y + 12, BOLD, 22, G.s900,
        { width: PILL_W - 12, align: "center" });
    // Label
    txt(s.label.toUpperCase(), px + 4, PILL_Y + PILL_H - 20, BOLD, 6, G.s500,
        { width: PILL_W - 8, align: "center", characterSpacing: 0.4 });
    // Mini progress bar
    const barY = PILL_Y + PILL_H - 9;
    rr(px + 8, barY, PILL_W - 16, 4, 2, G.s100);
    rr(px + 8, barY, Math.max(2, (PILL_W - 16) * s.value / 100), 4, 2, s.color);
  });

  setY(PILL_Y + PILL_H + 24);

  // ═════════════════════════════════════════════════════════════
  // SECTION — METADATA
  // ═════════════════════════════════════════════════════════════
  sectionHead("PAGE METADATA");

  const metaTitle = scan.metaData?.title || "Not found";
  const metaDesc  = scan.metaData?.description || "Not found";

  // Title row
  guard(52);
  rr(ML, getY(), CW, 44, 6, G.s50);
  rrStroke(ML, getY(), CW, 44, 6, G.s200);
  const mty = getY();
  txt("PAGE TITLE", ML + 12, mty + 8, BOLD, 7, G.s400, { characterSpacing: 0.7 });
  txt(metaTitle.substring(0, 72), ML + 12, mty + 19, BOLD, 9, G.s800);

  const tLen = metaTitle.length;
  const tOk  = tLen >= 30 && tLen <= 60;
  rr(PW - MR - 82, mty + 12, 76, 16, 8, tOk ? G.gTint : "#fffbeb");
  txt(tOk ? "Optimal length" : tLen < 30 ? "Too short" : "Too long",
      PW - MR - 80, mty + 17, BOLD, 7, tOk ? G.gDark : G.amber);

  addY(52);

  // Description row
  guard(60);
  const descH = Math.max(50, doc.heightOfString(metaDesc.substring(0, 200),
    { width: CW - 110, font: REG, fontSize: 8.5, lineGap: 2 }) + 24);
  rr(ML, getY(), CW, descH, 6, G.s50);
  rrStroke(ML, getY(), CW, descH, 6, G.s200);
  const mdy = getY();
  txt("META DESCRIPTION", ML + 12, mdy + 8, BOLD, 7, G.s400, { characterSpacing: 0.7 });
  doc.font(REG).fontSize(8.5).fillColor(G.s700)
     .text(metaDesc.substring(0, 200), ML + 12, mdy + 19, { width: CW - 110, lineGap: 2 });

  const dLen = metaDesc.length;
  const dOk  = dLen >= 120 && dLen <= 160;
  rr(PW - MR - 82, mdy + 12, 76, 16, 8, dOk ? G.gTint : "#fffbeb");
  txt(dOk ? "Optimal" : dLen < 120 ? "Too short" : "Too long",
      PW - MR - 80, mdy + 17, BOLD, 7, dOk ? G.gDark : G.amber);

  setY(mdy + descH + 14);

  // ═════════════════════════════════════════════════════════════
  // SECTION — HEADING STRUCTURE
  // ═════════════════════════════════════════════════════════════
  sectionHead("HEADING STRUCTURE");

  const h1s = scan.metaData?.headings?.h1 || [];
  const h2s = scan.metaData?.headings?.h2 || [];
  const h3s = scan.metaData?.headings?.h3 || [];
  const hStats = [
    { tag: "H1", count: h1s.length, ok: h1s.length === 1, sample: h1s[0], color: G.green  },
    { tag: "H2", count: h2s.length, ok: h2s.length >= 2,  sample: h2s[0], color: G.blue   },
    { tag: "H3", count: h3s.length, ok: true,              sample: h3s[0], color: G.purple },
  ];

  const HC_W = (CW - 16) / 3;
  guard(88);
  const hCardY = getY();

  hStats.forEach((h, i) => {
    const hx = ML + i * (HC_W + 8);
    rr(hx, hCardY, HC_W, 78, 6, G.white);
    rrStroke(hx, hCardY, HC_W, 78, 6, h.ok ? G.gMid : G.s200, 0.75);

    // Tag chip
    rr(hx + 10, hCardY + 10, 26, 16, 8, h.ok ? G.gTint : G.s100);
    txt(h.tag, hx + 14, hCardY + 14, BOLD, 8, h.ok ? G.green : G.s600);

    // Count
    txt(String(h.count), hx + 46, hCardY + 8, BOLD, 22, G.s900);

    // Status chip
    rr(hx + HC_W - 58, hCardY + 10, 50, 16, 8, h.ok ? G.gTint : "#fef9c3");
    txt(h.ok ? "Optimal" : "Review", hx + HC_W - 56, hCardY + 14, BOLD, 6.5,
        h.ok ? G.gDark : "#92400e");

    // Sample
    const sample = h.sample ? h.sample.substring(0, 28) + (h.sample.length > 28 ? "..." : "") : "None found";
    txt(`"${sample}"`, hx + 10, hCardY + 56, ITAL, 7, G.s400,
        { width: HC_W - 20, lineBreak: false });
  });

  setY(hCardY + 78 + 16);

  // ═════════════════════════════════════════════════════════════
  // SECTION — TECHNICAL SIGNALS
  // ═════════════════════════════════════════════════════════════
  sectionHead("TECHNICAL SEO SIGNALS");

  const ssl   = scan.summary?.sslSecure;
  const mob   = scan.summary?.mobileResponsive;
  const alts  = scan.metaData?.imagesWithoutAltCount || 0;
  const intL  = scan.summary?.linksAnalysis?.internalCount || 0;
  const extL  = scan.summary?.linksAnalysis?.externalCount || 0;
  const brkL  = scan.summary?.linksAnalysis?.brokenCount  || 0;

  const signals = [
    { label: "HTTPS / SSL",       ok: !!ssl,      pass: "Secure — HTTPS active",    fail: "No SSL certificate detected"  },
    { label: "Mobile Responsive", ok: !!mob,      pass: "Viewport tag detected",    fail: "No viewport meta tag found"   },
    { label: "Image Alt Tags",    ok: alts === 0, pass: "All images have alt text", fail: `${alts} image(s) missing alt` },
    { label: "Internal Links",    ok: intL > 0,   pass: `${intL} internal links`,   fail: "No internal links found"      },
    { label: "External Links",    ok: true,       pass: `${extL} external links`,   fail: "No external links found"      },
    { label: "Broken Links",      ok: brkL === 0, pass: "None detected",            fail: `${brkL} broken link(s) found` },
  ];

  const SIG_W = (CW - 10) / 2;
  let sigCol = 0;

  signals.forEach((sig, i) => {
    if (sigCol === 0) guard(34);
    const sx = ML + sigCol * (SIG_W + 10);
    const sy = getY();

    rr(sx, sy, SIG_W, 28, 6, sig.ok ? G.gTint : "#fff1f2");
    rrStroke(sx, sy, SIG_W, 28, 6, sig.ok ? G.gMid : "#fecdd3", 0.5);

    doc.circle(sx + 14, sy + 14, 5).fillColor(sig.ok ? G.green : G.rose).fill();
    txt(sig.label, sx + 24, sy + 6, BOLD, 7.5, G.s700);
    txt(sig.ok ? sig.pass : sig.fail, sx + 24, sy + 16, REG, 7,
        sig.ok ? G.gDark : G.rose);

    sigCol++;
    if (sigCol === 2) {
      sigCol = 0;
      addY(36);
    }
  });
  if (sigCol === 1) addY(36);
  addY(8);

  // ═════════════════════════════════════════════════════════════
  // SECTION — KEYWORD DENSITY
  // ═════════════════════════════════════════════════════════════
  const keywords = scan.summary?.keywordDensity || [];

  if (keywords.length > 0) {
    sectionHead("TOP KEYWORD DENSITY");

    const maxDensity = keywords[0]?.density || 1;

    keywords.forEach((kw, i) => {
      guard(28);
      const ky = getY();

      if (i % 2 === 0) {
        doc.rect(ML, ky, CW, 24).fillColor(G.s50).fill();
      }

      // Rank badge
      rr(ML + 4, ky + 4, 18, 16, 4, G.green);
      txt(String(i + 1), ML + 4, ky + 8, BOLD, 7.5, G.white,
          { width: 18, align: "center" });

      // Word
      txt(kw.word, ML + 28, ky + 7, BOLD, 9, G.s800);

      // Count
      txt(`${kw.count}x`, ML + 180, ky + 7, REG, 8, G.s500);

      // Bar
      const BAR_X = ML + 225;
      const BAR_W = 180;
      const filled = Math.max(2, BAR_W * (kw.density / maxDensity));
      rr(BAR_X, ky + 9, BAR_W, 6, 3, G.s200);
      rr(BAR_X, ky + 9, filled, 6, 3, G.green);

      // Density %
      txt(`${kw.density}%`, BAR_X + BAR_W + 8, ky + 7, BOLD, 7.5, G.s600);

      addY(24);
    });
    addY(8);
  }

  // ═════════════════════════════════════════════════════════════
  // SECTION — AI RECOMMENDATIONS
  // ═════════════════════════════════════════════════════════════
  sectionHead("AI-POWERED OPTIMIZATION RECOMMENDATIONS");

  const aiSummary = scan.aiSuggestions?.summary ||
    "Analysis complete. Review the actionable recommendations below.";

  // Executive summary callout
  const sumTextH = doc.heightOfString(aiSummary,
    { width: CW - 28, font: ITAL, fontSize: 9, lineGap: 2 });
  const sumBoxH = sumTextH + 32;

  guard(sumBoxH + 10);
  const sy = getY();

  rr(ML, sy, CW, sumBoxH, 8, G.gTint);
  doc.rect(ML, sy, 4, sumBoxH).fillColor(G.green).fill();
  rrStroke(ML, sy, CW, sumBoxH, 8, G.gMid, 0.6);

  txt("EXECUTIVE SUMMARY", ML + 16, sy + 10, BOLD, 7.5, G.green, { characterSpacing: 0.6 });
  doc.font(ITAL).fontSize(9).fillColor(G.s700)
     .text(aiSummary, ML + 16, sy + 24, { width: CW - 28, lineGap: 2 });

  setY(sy + sumBoxH + 14);

  // AI subsections
  const aiSections = [
    { title: "TECHNICAL FIXES",       color: G.indigo, bg: "#eef2ff", border: "#c7d2fe", items: scan.aiSuggestions?.technicalFixes || []       },
    { title: "CONTENT IMPROVEMENTS",  color: G.blue,   bg: "#f0f9ff", border: "#bae6fd", items: scan.aiSuggestions?.contentImprovements || []  },
    { title: "PERFORMANCE TIPS",      color: G.amber,  bg: "#fffbeb", border: "#fde68a", items: scan.aiSuggestions?.performanceTips || []       },
    { title: "PRIORITY ISSUES",       color: G.rose,   bg: "#fff1f2", border: "#fecdd3", items: scan.aiSuggestions?.priorityIssues || []        },
  ];

  aiSections.forEach((sec) => {
    if (!sec.items || sec.items.length === 0) return;

    // Calculate box height with accurate measurement
    let boxH = 30;
    sec.items.forEach((item) => {
      boxH += doc.heightOfString(`- ${item}`, {
        width: CW - 30, font: REG, fontSize: 8.5, lineGap: 2,
      }) + 7;
    });

    guard(boxH + 12);
    const bx = getY();

    rr(ML, bx, CW, boxH, 8, sec.bg);
    doc.rect(ML, bx, 4, boxH).fillColor(sec.color).fill();
    rrStroke(ML, bx, CW, boxH, 8, sec.border, 0.6);

    txt(sec.title, ML + 14, bx + 10, BOLD, 8, sec.color, { characterSpacing: 0.5 });

    let iy = bx + 26;
    sec.items.forEach((item) => {
      if (!item) return;
      const itemH = doc.heightOfString(`- ${item}`, {
        width: CW - 30, font: REG, fontSize: 8.5, lineGap: 2,
      }) + 7;

      if (iy + itemH > BOTTOM) {
        doc.addPage({ size: "A4", margin: 0 });
        pageNum++;
        drawPageChrome(false);
        iy = ML + 40;
      }

      doc.font(REG).fontSize(8.5).fillColor(G.s700)
         .text(`- ${item}`, ML + 16, iy, { width: CW - 28, lineGap: 2 });
      iy += itemH;
    });

    setY(bx + boxH + 12);
  });

  // ═════════════════════════════════════════════════════════════
  // CLOSING BADGE — fits on current page if 100px remain
  // ═════════════════════════════════════════════════════════════
  const BADGE_H = 70;
  guard(BADGE_H + 24);
  addY(16);

  const by = getY();
  rr(ML, by, CW, BADGE_H, 10, G.s900);

  // Subtle circles inside badge
  doc.circle(PW - MR - 44, by + BADGE_H / 2, 26).fillColor(G.s800).fill();
  doc.circle(ML + 30, by - 10, 20).fillColor(G.s800).fill();

  // Closing card — show the Search Pulse brand URL
  const brandUrl = "https://search-pulse.onrender.com/";
  txt("Search Pulse", ML + 22, by + 14, BOLD, 14, G.white);
  txt("Smart SEO Intelligence for modern websites.", ML + 22, by + 32, REG, 8, G.s400);
  txt(brandUrl, ML + 22, by + 47, BOLD, 7.5, G.green, { width: CW - SEAL_W - 40, lineBreak: false, ellipsis: true });

  // Redesigned seal — taller box, properly spaced text
  const SEAL_W = 74;
  const SEAL_H = 56;
  const sealX  = PW - MR - SEAL_W - 4;
  const sealY  = by + (BADGE_H - SEAL_H) / 2;
  rr(sealX, sealY, SEAL_W, SEAL_H, 8, G.green);
  // Top divider line inside seal
  doc.moveTo(sealX + 8, sealY + 18).lineTo(sealX + SEAL_W - 8, sealY + 18)
     .strokeColor(G.white).lineWidth(0.5).stroke();
  txt("SEO", sealX, sealY + 5, BOLD, 8, G.white,
      { width: SEAL_W, align: "center", characterSpacing: 1 });
  txt("AUDITED", sealX, sealY + 22, BOLD, 11, G.white,
      { width: SEAL_W, align: "center" });
  // Bottom divider
  doc.moveTo(sealX + 8, sealY + SEAL_H - 16).lineTo(sealX + SEAL_W - 8, sealY + SEAL_H - 16)
     .strokeColor(G.white).lineWidth(0.5).stroke();
  txt("CERTIFIED", sealX, sealY + SEAL_H - 12, BOLD, 5.5, G.white,
      { width: SEAL_W, align: "center", characterSpacing: 0.6 });

  // ── Done ──────────────────────────────────────────────────────
  doc.end();
};
